name = "elabela"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "DB"
database_name = "elabela-db"
database_id = "f4c9c7f9-2c70-4f36-8c90-8d591ca0f41a"