name = "elabela"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB" # Nome que usaremos no código
database_name = "elabela-db"
database_id = "f8f8f8f8-f8f8-f8f8-f8f8-f8f8f8f8f8f8" # Você precisará trocar pelo ID real gerado no painel da Cloudflare