name = "docker-dyad-template"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Variáveis de tempo de execução (Runtime)
NODE_VERSION = "20"

[build]
command = "pnpm run build"
path = ".vercel/output/static"

[build.vars]
# Variáveis exclusivas do momento do BUILD
NODE_VERSION = "20"
PNPM_VERSION = "9"
PNPM_FLAGS = "--no-frozen-lockfile"